// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestFullAppTemplate.Data.Context;

#nullable disable

namespace RestFullAppTemplate.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230329131746_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EPromoId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EPromoId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EPrize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EPromoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EPromoId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EPromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EPromoResult", b =>
                {
                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PrizeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EPrizeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EPromoId")
                        .HasColumnType("integer");

                    b.HasKey("ParticipantId", "PrizeId");

                    b.HasIndex("EPrizeId");

                    b.HasIndex("EPromoId");

                    b.ToTable("PromoResults");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EParticipant", b =>
                {
                    b.HasOne("RestFullAppTemplate.Data.Entities.EPromo", "EPromo")
                        .WithMany("Participants")
                        .HasForeignKey("EPromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EPromo");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EPrize", b =>
                {
                    b.HasOne("RestFullAppTemplate.Data.Entities.EPromo", "EPromo")
                        .WithMany("Prizes")
                        .HasForeignKey("EPromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EPromo");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EPromoResult", b =>
                {
                    b.HasOne("RestFullAppTemplate.Data.Entities.EPrize", "EPrize")
                        .WithMany()
                        .HasForeignKey("EPrizeId");

                    b.HasOne("RestFullAppTemplate.Data.Entities.EPromo", null)
                        .WithMany("PromoResults")
                        .HasForeignKey("EPromoId");

                    b.HasOne("RestFullAppTemplate.Data.Entities.EParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EPrize");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("RestFullAppTemplate.Data.Entities.EPromo", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Prizes");

                    b.Navigation("PromoResults");
                });
#pragma warning restore 612, 618
        }
    }
}
